# Generated by Django 5.2.7 on 2025-11-15 02:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='date_filled',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
