# Generated by Django 5.2 on 2025-04-09 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='type_of_assistance',
            field=models.CharField(choices=[('Medical', 'Medical'), ('Burial', 'Burial'), ('Transportation', 'Transportation'), ('Educational', 'Educational'), ('Others', 'Others')], max_length=50),
        ),
    ]
