# Generated by Django 5.1.6 on 2025-02-22 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_applicant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='address',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='full_name',
        ),
        migrations.AddField(
            model_name='applicant',
            name='age',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='applicant',
            name='barangay',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='applicant',
            name='city_municipality',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='applicant',
            name='civil_status',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Widowed', 'Widowed'), ('Separated', 'Separated')], default='Single', max_length=20),
        ),
        migrations.AddField(
            model_name='applicant',
            name='family_composition',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='first_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='applicant',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10),
        ),
        migrations.AddField(
            model_name='applicant',
            name='justification',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='last_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='applicant',
            name='middle_initial',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='occupation_income',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='province',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='applicant',
            name='purok_street',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='applicant',
            name='relationship_to_beneficiary',
            field=models.CharField(default='Self', max_length=100),
        ),
        migrations.AddField(
            model_name='applicant',
            name='social_worker_assessment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='type_of_assistance',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='contact_number',
            field=models.CharField(default='N/A', max_length=15),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='date_filled',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
