# Generated by Django 5.1.6 on 2025-04-12 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_applicant_type_of_assistance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='type_of_assistance',
            field=models.CharField(choices=[('Medical', 'Medical'), ('Burial', 'Burial'), ('Educational', 'Educational')], max_length=50),
        ),
    ]
