# Generated by Django 5.2.7 on 2025-11-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_applicant_date_filled'),
    ]

    operations = [
        migrations.AddField(
            model_name='representative',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
