# Generated by Django 5.1.6 on 2025-09-06 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_staffactivitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_assistance', models.CharField(max_length=50)),
                ('date_applied', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entry', to='api.applicant')),
                ('background_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='api.backgroundinfo')),
            ],
        ),
    ]
