# Generated by Django 5.1.6 on 2025-04-21 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_applicant_type_of_assistance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='justification',
        ),
    ]
