# Generated by Django 5.2.7 on 2025-11-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_representative_contact_number'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='applicant',
            index=models.Index(fields=['date_filled'], name='api_applica_date_fi_4314f6_idx'),
        ),
        migrations.AddIndex(
            model_name='applicant',
            index=models.Index(fields=['type_of_assistance'], name='api_applica_type_of_8fb6d8_idx'),
        ),
        migrations.AddIndex(
            model_name='applicant',
            index=models.Index(fields=['is_archived'], name='api_applica_is_arch_e99c4f_idx'),
        ),
        migrations.AddIndex(
            model_name='applicant',
            index=models.Index(fields=['latitude', 'longitude'], name='api_applica_latitud_2a9e90_idx'),
        ),
        migrations.AddIndex(
            model_name='applicant',
            index=models.Index(fields=['background_info'], name='api_applica_backgro_1b8f0a_idx'),
        ),
    ]
