# Generated by Django 5.1.6 on 2025-02-26 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_applicant_latitude_applicant_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='civil_status',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='family_composition',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='occupation_income',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='relationship_to_beneficiary',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='social_worker_assessment',
        ),
    ]
