# Generated by Django 5.2.7 on 2025-11-18 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_applicant_api_applica_date_fi_4314f6_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='applicant',
            name='api_applica_date_fi_4314f6_idx',
        ),
        migrations.RemoveIndex(
            model_name='applicant',
            name='api_applica_type_of_8fb6d8_idx',
        ),
        migrations.RemoveIndex(
            model_name='applicant',
            name='api_applica_is_arch_e99c4f_idx',
        ),
        migrations.RemoveIndex(
            model_name='applicant',
            name='api_applica_latitud_2a9e90_idx',
        ),
        migrations.RemoveIndex(
            model_name='applicant',
            name='api_applica_backgro_1b8f0a_idx',
        ),
    ]
