# Generated by Django 5.1.6 on 2025-04-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_applicant_justification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='beneficiary_name',
        ),
        migrations.AddField(
            model_name='applicant',
            name='applicant_type',
            field=models.CharField(choices=[('Self', 'Self'), ('Representative', 'Representative')], default='Self', max_length=20),
        ),
        migrations.AddField(
            model_name='applicant',
            name='other_valid_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='rep_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='rep_birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='rep_civil_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Widowed', 'Widowed'), ('Separated', 'Separated'), ('Divorced', 'Divorced')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='rep_first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='rep_gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='rep_last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='rep_middle_initial',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='rep_monthly_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='rep_occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='rep_relationship',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='rep_suffix',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
