# Generated by Django 5.1.6 on 2025-09-06 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_applicanthistory'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='backgroundinfo',
            unique_together={('first_name', 'last_name', 'birthday')},
        ),
    ]
