# Generated by Django 5.1.6 on 2025-09-06 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_backgroundinfo_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='background_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.backgroundinfo'),
        ),
    ]
