# Generated by Django 5.2.7 on 2025-11-24 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_applicant_api_applica_date_fi_4314f6_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicant',
            options={'ordering': ['-date_filled']},
        ),
        migrations.AddIndex(
            model_name='applicant',
            index=models.Index(fields=['latitude', 'longitude'], name='lat_lng_idx'),
        ),
        migrations.AddIndex(
            model_name='applicant',
            index=models.Index(fields=['type_of_assistance'], name='type_assist_idx'),
        ),
        migrations.AddIndex(
            model_name='applicant',
            index=models.Index(fields=['is_archived', 'date_filled'], name='archived_date_idx'),
        ),
        migrations.AddIndex(
            model_name='applicant',
            index=models.Index(fields=['-date_filled'], name='date_filled_desc_idx'),
        ),
    ]
