# Generated by Django 5.2.7 on 2025-12-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_applicant_options_applicant_lat_lng_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSummaryCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(max_length=255, unique=True)),
                ('data', models.JSONField()),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'indexes': [models.Index(fields=['cache_key', 'expires_at'], name='api_analyti_cache_k_5b876c_idx')],
            },
        ),
    ]
