# Generated by Django 5.1.6 on 2025-04-23 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
