# Generated by Django 5.1.6 on 2025-09-06 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_applicant_background_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='background_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.backgroundinfo'),
        ),
    ]
