# Generated by Django 5.2.7 on 2025-12-12 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_analyticssummarycache'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicanthistory',
            name='date_applied',
            field=models.DateTimeField(),
        ),
    ]
