# Generated by Django 5.1.6 on 2025-04-23 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_applicant_processed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
