# Generated by Django 5.1.6 on 2025-05-05 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_applicant_started_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='rep_address',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='rep_birthday',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='rep_civil_status',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='rep_first_name',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='rep_gender',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='rep_last_name',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='rep_middle_initial',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='rep_monthly_income',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='rep_occupation',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='rep_relationship',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='rep_suffix',
        ),
        migrations.CreateModel(
            name='Representative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_initial', models.CharField(blank=True, max_length=5, null=True)),
                ('suffix', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.TextField()),
                ('birthday', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('civil_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Widowed', 'Widowed'), ('Separated', 'Separated'), ('Divorced', 'Divorced')], max_length=20)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('monthly_income', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('relationship', models.CharField(max_length=100)),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.applicant')),
            ],
        ),
    ]
