# Generated by Django 5.2.7 on 2025-12-20 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_applicanthistory_date_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='identity_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='identity_status',
            field=models.CharField(choices=[('NEW', 'New'), ('VERIFIED', 'Verified'), ('SUSPICIOUS', 'Suspicious'), ('REVIEWED', 'Reviewed'), ('BLOCKED', 'Blocked')], db_index=True, default='NEW', max_length=20),
        ),
        migrations.AlterField(
            model_name='applicanthistory',
            name='date_applied',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
