# Generated by Django 5.1.6 on 2025-09-08 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_approval'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_name', models.CharField(max_length=255)),
                ('total_processed', models.IntegerField(default=0)),
                ('total_approved', models.IntegerField(default=0)),
                ('total_already_approved', models.IntegerField(default=0)),
                ('total_not_found', models.IntegerField(default=0)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_batches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
