# Generated by Django 5.2.7 on 2026-01-05 05:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_applicant_identity_notes_applicant_identity_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisbursementBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('assistance_type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payout_date', models.DateField(blank=True, null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DisbursementClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CLAIMED', 'Claimed'), ('UNCLAIMED', 'Unclaimed')], default='PENDING', max_length=20)),
                ('payout_date', models.DateField(blank=True, null=True)),
                ('signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='api.applicant')),
                ('approval', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='claim', to='api.approval')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='api.disbursementbatch')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
