# Generated by Django 5.1.6 on 2025-09-08 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_approvalbatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundinfo',
            name='middle_initial',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
