# Generated by Django 5.2.7 on 2026-01-05 05:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_disbursementbatch_disbursementclaim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disbursementbatch',
            name='is_closed',
        ),
        migrations.RemoveField(
            model_name='disbursementclaim',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='disbursementclaim',
            name='signature',
        ),
        migrations.RemoveField(
            model_name='disbursementclaim',
            name='verified_by',
        ),
        migrations.AddField(
            model_name='disbursementbatch',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=10),
        ),
        migrations.AddField(
            model_name='disbursementclaim',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='disbursementbatch',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='disbursementbatch',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='disbursementbatch',
            name='payout_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='disbursementclaim',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='disbursementclaim',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disbursement_claims', to='api.applicant'),
        ),
        migrations.AlterField(
            model_name='disbursementclaim',
            name='approval',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='disbursement_claim', to='api.approval'),
        ),
        migrations.AlterField(
            model_name='disbursementclaim',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='api.disbursementbatch'),
        ),
        migrations.AlterField(
            model_name='disbursementclaim',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CLAIMED', 'Claimed'), ('UNCLAIMED', 'Unclaimed')], default='PENDING', max_length=10),
        ),
    ]
