# Generated by Django 5.1.6 on 2025-05-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_customuser_last_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
