# Generated by Django 5.1.6 on 2025-09-08 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_backgroundinfo_middle_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='api.applicant'),
        ),
    ]
