# Generated by Django 5.2.7 on 2026-01-05 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_disbursementbatch_is_closed_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicanthistory',
            options={'ordering': ['-date_applied']},
        ),
        migrations.AddField(
            model_name='applicanthistory',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='applicanthistory',
            name='history_type',
            field=models.CharField(choices=[('APPLICATION', 'Application'), ('PAYOUT', 'Payout')], default='APPLICATION', max_length=20),
        ),
        migrations.AddField(
            model_name='applicanthistory',
            name='related_claim',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='history_record', to='api.disbursementclaim'),
        ),
    ]
