# Generated by Django 5.2.7 on 2026-01-08 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_applicanthistory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursementbatch',
            name='approval_batch',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disbursement_batch', to='api.approvalbatch'),
        ),
        migrations.AddField(
            model_name='disbursementbatch',
            name='finalized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disbursementbatch',
            name='total_beneficiaries',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='disbursementbatch',
            name='total_claimed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='disbursementbatch',
            name='total_unclaimed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='disbursementbatch',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('FINALIZED', 'Finalized')], default='OPEN', max_length=10),
        ),
    ]
