# Generated by Django 5.1.6 on 2025-09-08 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_approval_applicant'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='api.approvalbatch'),
        ),
    ]
