# Generated by Django 5.2.7 on 2026-01-10 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_disbursementbatch_approval_batch_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='approval',
            unique_together={('applicant', 'batch')},
        ),
    ]
