# Generated by Django 5.2.7 on 2026-01-10 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_approvalauditlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicanthistory',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='applicanthistory',
            name='related_claim',
        ),
        migrations.AlterField(
            model_name='applicanthistory',
            name='history_type',
            field=models.CharField(choices=[('APPLICATION', 'Application')], default='APPLICATION', max_length=20),
        ),
    ]
