# Generated by Django 5.2.7 on 2026-01-11 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_applicanthistory_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalbatch',
            name='file_hash',
            field=models.CharField(max_length=64, unique=True, null=True, blank=True,),
            preserve_default=False,
        ),
    ]
