# Generated by Django 5.2.7 on 2026-01-11 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_approvalbatch_file_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvalbatch',
            name='file_hash',
        ),
        migrations.AddField(
            model_name='approvalbatch',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('COMPLETED', 'Completed'), ('CLOSED', 'Closed')], default='OPEN', max_length=20),
        ),
        migrations.AlterField(
            model_name='approvalbatch',
            name='total_already_approved',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='approvalbatch',
            name='total_approved',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='approvalbatch',
            name='total_not_found',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='approvalbatch',
            name='total_processed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='approvalbatch',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
