# Generated by Django 5.2.7 on 2026-01-14 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_approvalbatch_file_hash_approvalbatch_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursementbatch',
            name='total_budget',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total budget allocated for this batch', max_digits=12),
        ),
    ]
